
server:
  port: 8880
spring:
  application:
    name: sschool-teacher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.243.54:3306/smart_school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: jjh1993
  redis:
    host: 47.94.243.54
    database: 0
    password: su284315
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 2
  jmx:
    default-domain: sschool_teacher

eureka:
  client:
    service-url:
      defaultZone: http://47.104.124.97:8080/eureka/
mybatis:
  mapper-locations: mapper/**/*.xml
logging:
  level:
    com.usoft.sschool_teacher.mapper: debug #,classpath:mapper/personal/*.xml
  #type-aliases-package: com.usoft.smartschool.pojo