
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.104.124.97:8080/eureka/
zuul:
  routes:
    sschool-manage:
      path: /webmanage/**
      url: http://47.104.124.97:8090/sschool_manage/
      ribbon:
    sschool-pub:
      path: /pub/**
      serviceId: http://47.104.124.97:8090/sschool_pub/
    sschool-student:
      path: /student/**
      serviceId: http://47.104.124.97:8090/sschool_student/
    sschool-teacher:
      path: /teacher/**
      serviceId: http://47.104.124.97:8090/sschool_teacher/
  strip-prefix: true

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  eureka:
    enabled: true
mybatis:
  mapper-locations: mapper/**/*.xml


server:
  port: 8090
spring:
  application:
    name: sschool-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.243.54:3306/smart_school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jjh1993
  redis:
    host: 47.94.243.54
    database: 0
    password: su284315
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 2
  #  resources:
  #    static-locations: classpath:static/,file:static/
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1100MB
  jmx:
    default-domain: sschool_zuul

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000