
server:
  port: 8090
spring:
  application:
    name: sschool-pub
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.243.54:3306/smart_school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jjh1993
  redis:
    host: 47.94.243.54
    database: 0
    password: su284315
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 10
        min-idle: 2
  jmx:
    default-domain: sschool_pub
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1100MB
eureka:
  client:
    service-url:
      defaultZone: http://47.104.124.97:8080/eureka/

mybatis:
  mapper-locations: com.usoft.sschool_pub.mapper.*
logging:
  level:
    com.usoft.sschool_pub.mapper: error